version: '3.8'
services:
    postgres:
        build:
            context: .
            dockerfile: postgres/Dockerfile
        ports:
            - 5434:5432
        environment:
            - POSTGRES_DB=dpla_exchange_cart_api
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=test

