version: '3.8'
services:
    # deploy:
    #    image: nypl/circ-webapp
    #    ports:
    #        - 5411:80
    #    environment:
    #        - SIMPLIFIED_PRODUCTION_DATABASE='postgres://simplified:test@postgres:5432/simplified_circ_db' 
    #        #- SIMPLIFIED_DB_TASK=""
    #    depends_on:
    #        - postgres
    #        - elasticsearch
    #    links:
    #        - postgres
    #        - elasticsearch

    # scripts:
    #     image: nypl/circ-scripts
    #     environment:
    #         - SIMPLIFIED_PRODUCTION_DATABASE='postgres://simplified:test@postgres:5432/simplified_circ_db' 
    #         - SIMPLIFIED_DB_TASK="init"
    #     depends_on:
    #         - postgres
    #     links:
    #         - postgres

    elasticsearch:
        build:
            context: .
            dockerfile: compose/elasticsearch/Dockerfile
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            -  discovery.type=single-node

    postgres:
        build:
            context: .
            dockerfile: compose/postgres/Dockerfile
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=simplified_circ_db
            - POSTGRES_USER=simplified
            - POSTGRES_PASSWORD=test
        volumes:
            - ./volumes:/var/lib/postgresql

    postgres_test:
        build:
            context: .
            dockerfile: compose/postgres/Dockerfile
        ports:
            - 5433:5432
        environment:
            - POSTGRES_DB=simplified_circ_db
            - POSTGRES_USER=simplified
            - POSTGRES_PASSWORD=test
        volumes:
            - ./volumes:/var/lib/postgresql

    minio:
        image: minio/minio
        ports:
            - 9000:9000
        environment:
            - "MINIO_ACCESS_KEY=minioadmin"
            - "MINIO_SECRET_KEY=minioadmin"
        command: server --address 0.0.0.0:9000 /data


volumes:
  db-data:

