version: '3.8'
services:
    elasticsearch:
        build:
            context: .
            dockerfile: elasticsearch/Dockerfile
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            -  discovery.type=single-node

    postgres:
        build:
            context: .
            dockerfile: postgres/Dockerfile
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=simplified_circ_db
            - POSTGRES_USER=simplified
            - POSTGRES_PASSWORD=test

    postgres_test:
        build:
            context: .
            dockerfile: postgres/Dockerfile
        ports:
            - 5433:5432
        environment:
            - POSTGRES_DB=simplified_circ_db
            - POSTGRES_USER=simplified
            - POSTGRES_PASSWORD=test

    minio:
        image: minio/minio
        ports:
            - 9000:9000
        environment:
            - "MINIO_ACCESS_KEY=minioadmin"
            - "MINIO_SECRET_KEY=minioadmin"
        command: server --address 0.0.0.0:9000 /data

    pypi:
        image: "pypiserver/pypiserver:latest"
        ports:
            - 44444:8080
        command: -P . -a . /data/packages

