FROM elasticsearch:6.4.0

WORKDIR /

# RUN /usr/share/elasticsearch/bin/plugin install analysis-icu
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu

EXPOSE 9200
EXPOSE 9300

